version: '3'
services:
    application:
        build:
            context: ./application
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        container_name: application
        volumes:
            - ./application:/usr/src/app
            - /usr/src/app/node_modules
    
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        container_name: client
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules