version: '3'
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        container_name: client
        volumes:
            - ./client:/usr/src/app
            - ./client/node_modules:/usr/src/app/node_modules